permalink: /:basename/

collections:
  success_stories:
    output: true
    permalink: /success-stories/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: none
  - scope:
      path: ""
      type: success_stories
    values:
      layout: success_story